/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hjss.hjss;

import HJSSData.BookingInfo;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Madar
 */
public class Attend extends javax.swing.JFrame {

    private int studentID;
    private int studentLevel;

    /**
     * Creates new form Attend
     */
    public Attend(int ID, int level) {
        initComponents();

        this.studentID = ID;
        this.studentLevel = level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitlle = new javax.swing.JLabel();
        jLabelbookingID = new javax.swing.JLabel();
        jTextFieldLearnerID = new javax.swing.JTextField();
        jLabelID1 = new javax.swing.JLabel();
        jTextFieldBookingID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        jButtonAttend = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitlle.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelTitlle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitlle.setText("ATTENDANCE");

        jLabelbookingID.setText("Enter Booking ID");

        jLabelID1.setText("Enter Learner ID");

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        jButtonAttend.setText("Attend");
        jButtonAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendActionPerformed(evt);
            }
        });

        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelbookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLearnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAttend, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitlle)
                .addGap(40, 40, 40)
                .addComponent(jTextFieldLearnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAttend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jLabelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(309, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //GET CSV   
    private List<BookingInfo> getBookingsFromCSV() {
        List<BookingInfo> bookingsList = new ArrayList<>();
        String filePath = "bookings.csv";
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 8) {
                    int id = Integer.parseInt(data[0]);
                    int Week = Integer.parseInt(data[1]);
                    String dayTime = data[2];
                    String Time = data[3];
                    String coachName = data[4];
                    int level = Integer.parseInt(data[5]);
                    String status = data[6];
                    String bookingID = data[7];
                    bookingsList.add(new BookingInfo(Week, dayTime, Time, coachName, level, id, status, bookingID));
                }
            }
        } catch (IOException e) {
            jTextAreaDisplay.setText("Error reading the bookings file: " + e.getMessage());
        }
        return bookingsList;
    }


    private void jButtonAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendActionPerformed
        // TODO add your handling code here:
        String learnerID = jTextFieldLearnerID.getText().trim();
        String bookingID = jTextFieldBookingID.getText().trim();
        boolean isMatchFound = false;

        List<BookingInfo> bookings = getBookingsFromCSV();
        System.out.println("Checking bookings for Learner ID: " + learnerID + " and Booking ID: " + bookingID);

        for (BookingInfo booking : bookings) {
            System.out.println("Found Booking - Learner ID: " + booking.studentID + ", Booking ID: " + booking.BookingID + ", Status: " + booking.status);
            // Ensure to check against the correct status
            if (String.valueOf(booking.studentID).equals(learnerID) && booking.BookingID.equals(bookingID) && booking.status.equals("Confirmed")) {
                booking.status = "Attended";
                isMatchFound = true;
                if (booking.studentLevel < 5) {
                    booking.studentLevel++;
                }
                System.out.println("Booking attended!");
                break;
            }
        }

        if (isMatchFound) {
            saveBookingsToCSV(bookings);
            jTextAreaDisplay.setText("Attendance confirmed for Booking ID: " + bookingID);
        } else {
            jTextAreaDisplay.setText("No matching booking found, or already attended.");
        }
    }//GEN-LAST:event_jButtonAttendActionPerformed
    private void incrementGrade(int studentID) {
        // Assuming studentLevel is fetched properly elsewhere and updated here
        if (studentLevel < 5) {
            studentLevel++;
            // Additional logic to update this level in your storage or display
            jTextAreaDisplay.append("\nGrade increased to " + studentLevel);
        }
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Menu mp = new Menu(studentID, studentLevel); // Use the studentID field here
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed
    private void saveBookingsToCSV(List<BookingInfo> bookings) {
        String filePath = "bookings.csv"; // Path to your CSV file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(filePath))) {
            for (BookingInfo booking : bookings) {
                // Format the string to write week information as well
                bw.write(String.format("%d,%d,%s,%s,%s,%d,%s,%s\n",
                        booking.studentID,
                        booking.Week, // Include the week in the CSV
                        booking.DayTime,
                        booking.Time,
                        booking.coachName,
                        booking.studentLevel,
                        booking.status,
                        booking.BookingID
                ));
            }
        } catch (IOException e) {
            jTextAreaDisplay.setText("Error writing to bookings file: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attend(00, 00).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButtonAttend;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelTitlle;
    private javax.swing.JLabel jLabelbookingID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JTextField jTextFieldBookingID;
    private javax.swing.JTextField jTextFieldLearnerID;
    // End of variables declaration//GEN-END:variables
}
