/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hjss.hjss;

import HJSSData.Coach;
import java.awt.Color;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author Madar
 */
public class BookSlot extends javax.swing.JFrame {

    // Variable and function Declarations
    //private HashSet<String> selectedDates = new HashSet<>();
    private HashMap<String, String> selectedDates;
    private int studentLevel;
    private int studentID;

    // Create an array to store Coach instances
    private Coach[] coaches = new Coach[]{
        new Coach("Coach A"),
        new Coach("Coach B"),
        new Coach("Coach C"),
        new Coach("Coach D")
    };
    // Counter for the current coach index
    private int currentCoachIndex = 0;

    /**
     * Creates new form BookSlot
     */
    public BookSlot(int level, int ID) {

        initComponents();
        // Disable Manual input to Calender 
        jDateChooser1.getDateEditor().setEnabled(false);
        // Retreive Student ID and Level From Main Page and set to label
        this.studentID = ID;
        jLabelStudentID.setText("Student ID: " + String.valueOf(ID));
        this.studentLevel = level;
        jLabelCurrentLvl.setText("Learner Level: " + String.valueOf(level));
        selectedDates = new HashMap<>();
        labelavailable.setText("Available Time Slots on Selected Date :");
        jList1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCurrentLvl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButtonBookSlot = new javax.swing.JButton();
        jLabelStudentID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        labelavailable = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCurrentLvl.setFont(new java.awt.Font("Bell MT", 0, 10)); // NOI18N
        jLabelCurrentLvl.setText("Current Level");

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Slot Booking");

        jButtonBookSlot.setText("Select Date");
        jButtonBookSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookSlotActionPerformed(evt);
            }
        });

        jLabelStudentID.setFont(new java.awt.Font("Bell MT", 0, 10)); // NOI18N
        jLabelStudentID.setText("Student ID");

        jScrollPane1.setViewportView(jList1);

        labelavailable.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        labelavailable.setForeground(new java.awt.Color(102, 102, 102));
        labelavailable.setText("label1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCurrentLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBookSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelavailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurrentLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBookSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookSlotActionPerformed
        // Get the selected date from jDateChooser
        Date selectedDate = jDateChooser1.getDate();
        labelavailable.setVisible(true);
        // Ensure a date is selected
        if (selectedDate == null) {
            System.out.println("No date selected.");
            return;
        }

        // Format the date to eliminate the time part and simplify comparison
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE dd MMM yyyy");
        String formattedDate = sdf.format(selectedDate);

        // Check if the date is already booked
        if (selectedDates.containsKey(formattedDate)) {
            System.out.println("Date Already Booked");
            return;
        }

        // Prepare the model for jList1
        DefaultListModel<String> model = new DefaultListModel<>();
        // Set calendar time to the selected date to check the day of week
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(selectedDate);
        int dayOfWeek = calendar.get(Calendar.DAY_OF_WEEK);

        // Checking the day of the week to determine if it's a valid booking day
        if (dayOfWeek == Calendar.MONDAY || dayOfWeek == Calendar.WEDNESDAY || dayOfWeek == Calendar.FRIDAY) {
            System.out.println("It's Monday, Wednesday, or Friday.");            
            jList1.setVisible(true);
// Logic to check and handle specific time slots goes here.
            // For example, check if the selected time is between 4-7pm.
            model.addElement("4-5pm");
            model.addElement("5-6pm");
            model.addElement("6-7pm");

        } else if (dayOfWeek == Calendar.SATURDAY) {
            System.out.println("It's Saturday.");
            jList1.setVisible(true);
            // Logic to check and handle specific time slots for Saturday goes here.
            // For example, check if the selected time is between 2-4pm.
            // This part of the logic is not shown as jDateChooser1 does not include time selection.
            model.addElement("2-3pm");
            model.addElement("3-4pm");

        } else {
            System.out.println("Fail - Selected day is not available for lessons.");
            labelavailable.setText("Fail - Selected day is not available for lessons.");
            labelavailable.setForeground(Color.red);
            
            return;
        }
        
        
        
    // Set the model to jList1 to display the time slots
    jList1.setModel(model);
    jList1.setEnabled(true); // Make sure the list is enabled if it was previously disabled
        // Assuming the time slot is valid, proceed with booking
        selectedDates.put(formattedDate, ""); // Use an empty string or relevant info as the value
        System.out.println("Booking Success: " + selectedDates);

        // Assign a coach in sequence
        Coach assignedCoach = coaches[currentCoachIndex];
        System.out.println("Assigned Coach: " + assignedCoach.getCname());
        currentCoachIndex = (currentCoachIndex + 1) % coaches.length;
    }//GEN-LAST:event_jButtonBookSlotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSlot(000, 000).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookSlot;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCurrentLvl;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labelavailable;
    // End of variables declaration//GEN-END:variables
}
