/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hjss.hjss;

import HJSSData.BookingInfo;
import HJSSData.Coach;
import java.awt.Color;
import java.io.*;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Madar
 */
public class BookSlot extends javax.swing.JFrame {

    // Variable and function Declarations
    // Stores student ID and their list of bookings
    private HashMap<Integer, List<BookingInfo>> studentBookings;
    private int studentLevel;
    private int studentID;

    /**
     * Creates new form BookSlot CONSTRUCTOR OF BOOKINGSLOT PAGE
     */
    public BookSlot(int ID, int level) {
        initComponents();
        this.studentID = ID; // Ensure this line sets the member variable correctly
        jLabelStudentID.setText("Student ID: " + String.valueOf(ID));
        this.studentLevel = level;
        jLabelCurrentLvl.setText("Learner Level: " + String.valueOf(level));
        // Initialize the studentBookings HashMap
        studentBookings = new HashMap<>();

        //Update time asper coach
        comboBoxCoachName.setModel(new DefaultComboBoxModel<>(getCoachNames()));
        comboBoxCoachName.setSelectedIndex(0); // Set to the first coach

    }

    //method to get coach names 
    private String[] getCoachNames() {
        return new String[]{"Coach A", "Coach B", "Coach C", "Coach D"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCurrentLvl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelStudentID = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        comboBoxDay = new javax.swing.JComboBox<>();
        jLabelGrade = new javax.swing.JLabel();
        comboBoxGradeLevel = new javax.swing.JComboBox<>();
        labelCoachName = new javax.swing.JLabel();
        comboBoxCoachName = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetails = new javax.swing.JTextArea();
        jButtonBook = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabelWeek = new javax.swing.JLabel();
        jComboBoxWeek = new javax.swing.JComboBox<>();
        jLabeltime = new javax.swing.JLabel();
        jComboBoxTime = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelCurrentLvl.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jLabelCurrentLvl.setText("Current Level");

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Slot Booking");

        jLabelStudentID.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jLabelStudentID.setText("Student ID");

        jLabelDay.setText("Day");

        comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDayActionPerformed(evt);
            }
        });

        jLabelGrade.setText("Grade Level Selection");

        comboBoxGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelCoachName.setText("Coach Name Selection");

        comboBoxCoachName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCoachName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCoachNameActionPerformed(evt);
            }
        });

        textAreaDetails.setEditable(false);
        textAreaDetails.setColumns(20);
        textAreaDetails.setRows(5);
        jScrollPane1.setViewportView(textAreaDetails);

        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });

        Back.setText("Go Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabelWeek.setText("Week");

        jComboBoxWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabeltime.setText("Time");

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabelCurrentLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCoachName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxCoachName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jComboBoxWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurrentLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay)
                    .addComponent(jLabeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCoachName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboBoxCoachName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBook)))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGrade)
                            .addComponent(comboBoxGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Wednesday", "Friday", "Saturday" }));
        comboBoxGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        comboBoxCoachName.setModel(new DefaultComboBoxModel<>(getCoachNames()));
        jComboBoxWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookLesson() {
        //Get values from Combo box
        String selectedDay = (String) comboBoxDay.getSelectedItem();
        String selectedTime = (String) jComboBoxTime.getSelectedItem();
        int selectedGradeLevel = Integer.parseInt(comboBoxGradeLevel.getSelectedItem().toString());
        String selectedCoachName = (String) comboBoxCoachName.getSelectedItem();
        int Week = Integer.parseInt(jComboBoxWeek.getSelectedItem().toString());
        String status = "Pending";

        // Validate time and coach compatibility
        if (!isTimeCompatibleWithCoach(selectedTime, selectedCoachName)) {
            JOptionPane.showMessageDialog(this, "This coach is not available at the selected time.", "Booking Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Check if the selected grade level is appropriate
        if (selectedGradeLevel > studentLevel + 1 || selectedGradeLevel < studentLevel) {
            JOptionPane.showMessageDialog(this, "You can only book lessons for your current level or one level higher.", "Grade Level Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if the grade level is not correct
        }
        // Check for duplicate bookings
        if (isDuplicateOrLimitReached(Week, selectedDay, selectedTime)) {
            return;
        }

        status = "booked";
        String bookingID = BookingInfo.generateBookingID();
        // Proceed to check availability and potentially book the lesson
        BookingInfo newBooking = new BookingInfo(Week, selectedDay, selectedTime, selectedCoachName, selectedGradeLevel, studentID, status);

        // Ensure the list for this studentID is initialized
        List<BookingInfo> bookingsList = studentBookings.getOrDefault(studentID, new ArrayList<>());
        bookingsList.add(newBooking);

        //add list and student id to hashmap
        studentBookings.put(studentID, bookingsList); // Save the new booking list
        //save to CSV file function
        saveBookingToFile(newBooking);
        textAreaDetails.setText("Booking Confirmed with ID: " + newBooking.BookingID + "\nWeek: " + Week + "\nDay: " + selectedDay + "\nTime: " + selectedTime + "\nCoach: " + selectedCoachName + "\nGrade: " + selectedGradeLevel + "\nLearner ID: " + studentID);
    }

    //method to check if the selected time is compatible with the coach
    private boolean isTimeCompatibleWithCoach(String time, String coach) {
        switch (coach) {
            case "Coach A":
                return "4-5pm".equals(time);
            case "Coach B":
                return "5-6pm".equals(time);
            case "Coach C":
                return "6-7pm".equals(time);
            case "Coach D":
                return "2-3pm".equals(time) || "3-4pm".equals(time);
            default:
                return false;
        }
    }

    //Function for isDuplicateOrLimitReached
    private boolean isDuplicateOrLimitReached(int week, String day, String time) {
        // Get the bookings for the current student or initialize if not present
        List<BookingInfo> bookingsList = studentBookings.get(studentID);
        if (bookingsList == null) {
            bookingsList = new ArrayList<>(); // Initialize if null
            studentBookings.put(studentID, bookingsList); // Add to the map
        }

        for (BookingInfo booking : bookingsList) {
            if (booking.Week == week && booking.DayTime.equals(day) && booking.Time.equals(time)) {
                JOptionPane.showMessageDialog(this, "You have already booked this slot.", "Booking Error", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        }
        return false;
    }

    private List<BookingInfo> getBookingsFromCSV() {
        List<BookingInfo> bookingsList = new ArrayList<>();  // Initialize the list here
        String filePath = "bookings.csv"; // Ensure this is the correct path to your CSV file
        File file = new File(filePath);

        // Check if the file exists to handle the case where no bookings have been saved yet
        if (!file.exists()) {
            return bookingsList;  // Return the empty list if no file exists
        }

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 8) { // Ensure there are eight elements
                    try {
                        int id = Integer.parseInt(data[0]);
                        int Week = Integer.parseInt(data[1]);
                        String dayTime = data[2];
                        String Time = data[3];
                        String coachName = data[4];
                        int level = Integer.parseInt(data[5]);
                        String status = data[6];
                        String bookingID = data[7];
                        BookingInfo booking = new BookingInfo(Week, dayTime, Time, coachName, level, id, status, bookingID);
                        bookingsList.add(booking);
                    } catch (NumberFormatException e) {
                        System.out.println("Error parsing booking data: " + e.getMessage());
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading the bookings file: " + e.getMessage());
        }
        return bookingsList;
    }

    // SAVE TO CSV
    private void saveBookingToFile(BookingInfo booking) {
        String filePath = "bookings.csv"; // The path to the CSV file
        File file = new File(filePath);

        try (FileWriter fw = new FileWriter(filePath, true); // Open the file in append mode
                 BufferedWriter bw = new BufferedWriter(fw); PrintWriter out = new PrintWriter(bw)) {

            // Check if the file is new or empty and needs headers
            if (!file.exists() || file.length() == 0) {
                // Write headers
                out.println("StudentID,Week,DayTime,Time,CoachName,StudentLevel,Status,BookingID");
            }
            // Write the booking to the CSV file
            out.println(booking.studentID + ","
                    + booking.Week + ","
                    + booking.DayTime + ","
                    + booking.Time + ","
                    + booking.coachName + ","
                    + booking.studentLevel + ","
                    + booking.status + ","
                    + booking.BookingID);
        } catch (IOException e) {
            System.out.println("Error writing to bookings file: " + e.getMessage());
            // Optionally display an error message dialog
            JOptionPane.showMessageDialog(null, "Error writing to bookings file: " + e.getMessage(), "File Writing Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        // TODO add your handling code here:
        bookLesson();
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Menu mp = new Menu(studentID, studentLevel); // Use the studentID field here
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void jComboBoxTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTimeActionPerformed

    // This method updates the time comboBox based on the selected day
    private void updateTimesBasedOnDayAndCoach() {
        String selectedDay = (String) comboBoxDay.getSelectedItem();
        String selectedCoach = (String) comboBoxCoachName.getSelectedItem();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        if ("Coach D".equals(selectedCoach) && "Saturday".equals(selectedDay)) {
            model.addElement("2-3pm");
            model.addElement("3-4pm");
        } else if (!"Saturday".equals(selectedDay)) {
            switch (selectedCoach) {
                case "Coach A":
                    model.addElement("4-5pm");
                    break;
                case "Coach B":
                    model.addElement("5-6pm");
                    break;
                case "Coach C":
                    model.addElement("6-7pm");
                    break;
            }
        }

        jComboBoxTime.setModel(model);
    }

    private void comboBoxDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDayActionPerformed
        // TODO add your handling code here:
        updateTimesBasedOnDayAndCoach();
    }//GEN-LAST:event_comboBoxDayActionPerformed

    private void comboBoxCoachNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCoachNameActionPerformed
        // TODO add your handling code here:
        updateTimesBasedOnDayAndCoach();
    }//GEN-LAST:event_comboBoxCoachNameActionPerformed
//    private void updateTimesBasedOnCoach() {
//        String selectedCoach = comboBoxCoachName.getSelectedItem().toString();
//        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
//
//        switch (selectedCoach) {
//            case "Coach A":
//                model.addElement("4-5pm");
//                break;
//            case "Coach B":
//                model.addElement("5-6pm");
//                break;
//            case "Coach C":
//                model.addElement("6-7pm");
//                break;
//            case "Coach D":
//                model.addElement("2-3pm");
//                model.addElement("3-4pm");
//                break;
//        }
//
//        jComboBoxTime.setModel(model);
//    }
//
// 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSlot(000, 000).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> comboBoxCoachName;
    private javax.swing.JComboBox<String> comboBoxDay;
    private javax.swing.JComboBox<String> comboBoxGradeLevel;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JComboBox<String> jComboBoxTime;
    private javax.swing.JComboBox<String> jComboBoxWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCurrentLvl;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelGrade;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JLabel jLabelWeek;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCoachName;
    private javax.swing.JTextArea textAreaDetails;
    // End of variables declaration//GEN-END:variables
}
