/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hjss.hjss;

import HJSSData.BookingInfo;
import HJSSData.Coach;
import java.awt.Color;
import java.io.*;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Madar
 */
public class BookSlot extends javax.swing.JFrame {

    // Variable and function Declarations
    // Stores student ID and their list of bookings
    private HashMap<Integer, List<BookingInfo>> studentBookings;
    private int studentLevel;
    private int studentID;

    /**
     * Creates new form BookSlot CONSTRUCTOR OF BOOKINGSLOT PAGE
     */
    public BookSlot(int ID, int level) {
        initComponents();
        this.studentID = ID; // Ensure this line sets the member variable correctly
        jLabelStudentID.setText("Student ID: " + String.valueOf(ID));
        this.studentLevel = level;
        jLabelCurrentLvl.setText("Learner Level: " + String.valueOf(level));
        // Initialize the studentBookings HashMap
        studentBookings = new HashMap<>();
    }

    //method to get coach names 
    private String[] getCoachNames() {
        return new String[]{"Coach A", "Coach B", "Coach C", "Coach D"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCurrentLvl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelStudentID = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        comboBoxDay = new javax.swing.JComboBox<>();
        jLabelGrade = new javax.swing.JLabel();
        comboBoxGradeLevel = new javax.swing.JComboBox<>();
        labelCoachName = new javax.swing.JLabel();
        comboBoxCoachName = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetails = new javax.swing.JTextArea();
        jButtonBook = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelCurrentLvl.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jLabelCurrentLvl.setText("Current Level");

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Slot Booking");

        jLabelStudentID.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jLabelStudentID.setText("Student ID");

        jLabelDay.setText("Day");

        comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelGrade.setText("Grade Level Selection");

        comboBoxGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelCoachName.setText("Coach Name Selection");

        comboBoxCoachName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textAreaDetails.setEditable(false);
        textAreaDetails.setColumns(20);
        textAreaDetails.setRows(5);
        jScrollPane1.setViewportView(textAreaDetails);

        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });

        Back.setText("Go Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabelCurrentLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelCoachName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxCoachName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(81, 81, 81)
                                .addComponent(jButtonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurrentLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDay)
                    .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGrade)
                    .addComponent(comboBoxGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoachName)
                    .addComponent(comboBoxCoachName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday 9am - 10pm", "Wednesday 9am - 10pm", "Friday 9am - 10pm", "Saturday 9am - 10pm" }));
        comboBoxGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        comboBoxCoachName.setModel(new DefaultComboBoxModel<>(getCoachNames()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookLesson() {
        //Get values from Combo box
        String selectedDay = (String) comboBoxDay.getSelectedItem();
        int selectedGradeLevel = Integer.parseInt(comboBoxGradeLevel.getSelectedItem().toString());
        String selectedCoachName = (String) comboBoxCoachName.getSelectedItem();
        String status = "Pending";

        // Check if the selected grade level is appropriate
        if (selectedGradeLevel > studentLevel + 1 || selectedGradeLevel < studentLevel) {
            JOptionPane.showMessageDialog(this, "You can only book lessons for your current level or one level higher.", "Grade Level Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if the grade level is not correct
        }
        // Check for duplicate and limit
        if (isDuplicateOrLimitReached(selectedDay, selectedCoachName)) {
            return; // Exit if a duplicate booking exists or limit is reached
        }
        String bookingID = BookingInfo.generateBookingID();
        // Proceed to check availability and potentially book the lesson
        BookingInfo newBooking = new BookingInfo(selectedDay, selectedCoachName, selectedGradeLevel, studentID, status);
        //create new list  
        List<BookingInfo> bookingsList = studentBookings.getOrDefault(studentID, new ArrayList<>());
        bookingsList.add(newBooking);
        //add list and student id to hashmap
        studentBookings.put(studentID, bookingsList); // Save the new booking list
        //save to CSV file function
        saveBookingToFile(newBooking);
        textAreaDetails.setText("Booking Confirmed with ID: " + newBooking.BookingID + "\nDay & Time: " + selectedDay + "\nCoach: " + selectedCoachName + "\nGrade: " + selectedGradeLevel + "\nLearner ID: " + studentID);

    }

    //Function for isDuplicateOrLimitReached
    private boolean isDuplicateOrLimitReached(String selectedDay, String selectedCoachName) {
        List<BookingInfo> bookingsList = studentBookings.get(studentID);

        if (bookingsList != null) {
            if (bookingsList.size() >= 4) {
                JOptionPane.showMessageDialog(this, "You have reached the maximum number of bookings allowed.", "Booking Limit Reached", JOptionPane.WARNING_MESSAGE);
                return true;
            }

            for (BookingInfo booking : bookingsList) {
                if (booking.DayTime.equals(selectedDay) && booking.coachName.equals(selectedCoachName)) {
                    JOptionPane.showMessageDialog(this, "You have already booked this time slot.", "Duplicate Booking", JOptionPane.WARNING_MESSAGE);
                    return true;
                }
            }
        }

        return false;
    }

    // SAVE TO CSV
    private void saveBookingToFile(BookingInfo booking) {
        String filePath = "bookings.csv"; // The path to the CSV file

        try (FileWriter fw = new FileWriter(filePath, true); // Open the file in append mode
                 BufferedWriter bw = new BufferedWriter(fw); PrintWriter out = new PrintWriter(bw)) {
            // Write the booking to the CSV file including the status
            out.println(booking.studentID + ","
                    + booking.DayTime + ","
                    + booking.coachName + ","
                    + booking.studentLevel + ","
                    + booking.status + ","
                    + booking.BookingID);
        } catch (IOException e) {
            e.printStackTrace(); // Properly handle this exception
        }
    }

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        // TODO add your handling code here:
        bookLesson();
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Menu mp = new Menu(studentID, studentLevel); // Use the studentID field here
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSlot(000, 000).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> comboBoxCoachName;
    private javax.swing.JComboBox<String> comboBoxDay;
    private javax.swing.JComboBox<String> comboBoxGradeLevel;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCurrentLvl;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelGrade;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCoachName;
    private javax.swing.JTextArea textAreaDetails;
    // End of variables declaration//GEN-END:variables
}
