/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hjss.hjss;

import HJSSData.BookingInfo;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Madar
 */
public class ViewBookings extends javax.swing.JFrame {

    private int studentLevel;
    private int studentID;

    /**
     * Creates new form ViewBookings
     */
    public ViewBookings(int ID, int level) {
        initComponents();
        this.studentID = ID;
        this.studentLevel = level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitlle = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldLearnerID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaViewAllBookings = new javax.swing.JTextArea();
        jButtonSearch = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitlle.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelTitlle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitlle.setText("View Bookings");

        jLabelID.setText("Enter Learner ID");

        jTextAreaViewAllBookings.setColumns(20);
        jTextAreaViewAllBookings.setRows(5);
        jScrollPane1.setViewportView(jTextAreaViewAllBookings);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabelTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLearnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitlle)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLearnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButtondelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String studentIdInput = jTextFieldLearnerID.getText().trim();
        if (!studentIdInput.isEmpty()) {
            try {
                int studentId = Integer.parseInt(studentIdInput);
                List<BookingInfo> allBookings = getBookingsFromCSV();
                List<BookingInfo> filteredBookings = new ArrayList<>();
                for (BookingInfo booking : allBookings) {
                    if (booking.studentID == studentId) {
                        filteredBookings.add(booking);
                    }
                }
                displayBookings(filteredBookings);
            } catch (NumberFormatException e) {
                jTextAreaViewAllBookings.setText("Invalid ID format. Please enter a numeric ID.");
            }
        } else {
            jTextAreaViewAllBookings.setText("Please enter a Student ID.");
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Menu mp = new Menu(studentID, studentLevel); // Use the studentID field here
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    ////////////DELETE FUNCTIONS ////////////////////////////////////   
    private void deleteAllBookingsForStudent(int studentId) {
        List<BookingInfo> allBookings = getBookingsFromCSV();
        List<BookingInfo> updatedBookings = new ArrayList<>();

        // Filter out bookings for the given student ID
        for (BookingInfo booking : allBookings) {
            if (booking.studentID != studentId) {
                updatedBookings.add(booking);
            }
        }

        // Save the updated list back to CSV
        saveBookingsToCSV(updatedBookings);
    }

    private void saveBookingsToCSV(List<BookingInfo> bookings) {
        String filePath = "bookings.csv";
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(filePath, false))) { // False to overwrite the file
            for (BookingInfo booking : bookings) {
                bw.write(booking.studentID + "," + booking.DayTime + "," + booking.coachName + "," + booking.studentLevel + "," + booking.status + "\n");
            }
        } catch (IOException e) {
            jTextAreaViewAllBookings.setText("Error writing to bookings file: " + e.getMessage());
        }
    }

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        String studentIdInput = jTextFieldLearnerID.getText().trim();
        if (!studentIdInput.isEmpty()) {
            try {
                int studentId = Integer.parseInt(studentIdInput);
                deleteAllBookingsForStudent(studentId);
                jTextAreaViewAllBookings.setText("All bookings deleted for Student ID: " + studentId);
            } catch (NumberFormatException e) {
                jTextAreaViewAllBookings.setText("Invalid ID format. Please enter a numeric ID.");
            }
        } else {
            jTextAreaViewAllBookings.setText("Please enter a Student ID.");
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    ////////////////retreive data from CSV  ////////////////////////////////
    private List<BookingInfo> getBookingsFromCSV() {
        List<BookingInfo> bookingsList = new ArrayList<>();
        String filePath = "bookings.csv"; // Ensure this is the correct path to your CSV file
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 5) {
                    int id = Integer.parseInt(data[0]);
                    String dayTime = data[1];
                    String coachName = data[2];
                    int level = Integer.parseInt(data[3]);
                    String status = data[4];
                    bookingsList.add(new BookingInfo(dayTime, coachName, level, id, status));
                }
            }
        } catch (IOException e) {
            jTextAreaViewAllBookings.setText("Error reading the bookings file: " + e.getMessage());
        }
        return bookingsList;
    }
    //////////////////////Display all the data ////////////////

    private void displayBookings(List<BookingInfo> bookings) {
        if (bookings.isEmpty()) {
            jTextAreaViewAllBookings.setText("No bookings found for Student ID: " + jTextFieldLearnerID.getText());
        } else {
            StringBuilder sb = new StringBuilder();
            for (BookingInfo booking : bookings) {
                sb.append(booking.toString()).append("\n");
            }
            jTextAreaViewAllBookings.setText(sb.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBookings(00, 00).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelTitlle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaViewAllBookings;
    private javax.swing.JTextField jTextFieldLearnerID;
    // End of variables declaration//GEN-END:variables
}
