/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hjss.hjss;

import HJSSData.BookingInfo;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Madar
 */
public class ViewBookings extends javax.swing.JFrame {

    private int studentLevel;
    private int studentID;

    /**
     * Creates new form ViewBookings
     */
    public ViewBookings(int ID, int level) {
        initComponents();
        this.studentID = ID;
        this.studentLevel = level;
        UpdatePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitlle = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldLearnerID = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        bookingComboBox = new javax.swing.JComboBox<>();
        jLabelID1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        UpdatePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTime = new javax.swing.JComboBox<>();
        updatechangebooking = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitlle.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelTitlle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitlle.setText("View Bookings");

        jLabelID.setText("Enter Learner ID");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        bookingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelID1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelID1.setText("Bookings");

        jToggleButton1.setText("Change Booking");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Update / Modify Booking");

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        updatechangebooking.setText("Update");
        updatechangebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatechangebookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatePanelLayout = new javax.swing.GroupLayout(UpdatePanel);
        UpdatePanel.setLayout(UpdatePanelLayout);
        UpdatePanelLayout.setHorizontalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatechangebooking, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(621, Short.MAX_VALUE))
        );
        UpdatePanelLayout.setVerticalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatechangebooking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2-3pm", "3-4pm", "4-5pm", "5-6pm","6-7pm" }));

        jButtonCancel.setText("Cancel Booking");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLearnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelID1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jToggleButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel))
                    .addComponent(UpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitlle)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLearnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(UpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        bookingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String studentIdInput = jTextFieldLearnerID.getText().trim();
        if (!studentIdInput.isEmpty()) {
            try {
                int studentId = Integer.parseInt(studentIdInput);
                List<BookingInfo> filteredBookings = new ArrayList<>();
                for (BookingInfo booking : getBookingsFromCSV()) {
                    if (booking.studentID == studentId) {
                        filteredBookings.add(booking);
                    }
                }
                displayBookings(filteredBookings);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid ID format. Please enter a numeric ID", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Menu mp = new Menu(studentID, studentLevel); // Use the studentID field here
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed
    ////////////////retreive data from CSV  ////////////////////////////////
    private List<BookingInfo> getBookingsFromCSV() {
        List<BookingInfo> bookingsList = new ArrayList<>();
        String filePath = "bookings.csv"; // Ensure this is the correct path to your CSV file
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 8) { // Ensure there are seven elements (including BookingID and Week)
                    try {
                        int id = Integer.parseInt(data[0]);
                        int Week = Integer.parseInt(data[1]);
                        String dayTime = data[2];
                        String Time = data[3];
                        String coachName = data[4];
                        int level = Integer.parseInt(data[5]);
                        String status = data[6];
                        String bookingID = data[7];
                        BookingInfo booking = new BookingInfo(Week, dayTime, Time, coachName, level, id, status, bookingID);
                        bookingsList.add(booking);
                    } catch (NumberFormatException e) {
                        // Handle the case where parsing fails
                        System.out.println("Error parsing booking data: " + e.getMessage());
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading the bookings file: " + e.getMessage());
        }
        return bookingsList;
    }

    //////////////////////Display all the data ////////////////
    private void displayBookings(List<BookingInfo> bookings) {
        bookingComboBox.removeAllItems(); // Clear the combo box before adding items
        if (bookings.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No bookings found.");
            jButtondelete.setEnabled(false);
            jButtonCancel.setEnabled(false);
            jToggleButton1.setEnabled(false);
        } else {
            for (BookingInfo booking : bookings) {
                bookingComboBox.addItem(booking.toString());
            }
            jButtondelete.setEnabled(true);
            jButtonCancel.setEnabled(true);
            jToggleButton1.setEnabled(true);
        }
    }

    ////////////DELETE FUNCTIONS ////////////////////////////////////   
    private void saveBookingsToCSV(List<BookingInfo> bookings) {
        String filePath = "bookings.csv";
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(filePath, false))) {
            for (BookingInfo booking : bookings) {
                bw.write(booking.studentID + "," + booking.Week + "," + booking.DayTime + "," + booking.Time + "," + booking.coachName + "," + booking.studentLevel + "," + booking.status + "," + booking.BookingID + "\n");
            }
        } catch (IOException e) {
            System.out.println("Error writing to bookings file: " + e.getMessage());
        }
    }


    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = bookingComboBox.getSelectedIndex();
        if (selectedIndex >= 0) {
            List<BookingInfo> allBookings = getBookingsFromCSV();
            if (!allBookings.isEmpty() && selectedIndex < allBookings.size()) {
                allBookings.remove(selectedIndex);
                saveBookingsToCSV(allBookings);
                reloadBookingsFromCSV(); // Reload the bookings from CSV
                JOptionPane.showMessageDialog(this, "Booking Deleted successfully !!.");
            }
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void reloadBookingsFromCSV() {
    List<BookingInfo> allBookings = getBookingsFromCSV();
    displayBookings(allBookings); // Refresh the ComboBox with updated list
}
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        boolean isVisible = UpdatePanel.isVisible();
        // Toggle the visibility    
        UpdatePanel.setVisible(!isVisible);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void updatechangebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatechangebookingActionPerformed
        // Get the index of the selected booking
        int selectedIndex = bookingComboBox.getSelectedIndex();
        if (selectedIndex >= 0) {
            List<BookingInfo> allBookings = getBookingsFromCSV();
            BookingInfo selectedBooking = allBookings.get(selectedIndex);
            String newTime = (String) jComboBoxTime.getSelectedItem();

            // Update the booking time
            selectedBooking.Time = newTime;
            selectedBooking.status = "booked";
            // Save the updated bookings back to the CSV
            saveBookingsToCSV(allBookings);
            JOptionPane.showMessageDialog(this, "Booking updated successfully.");
            displayBookings(allBookings); // Refresh the ComboBox display
            cleardisplay();

        } else {
            JOptionPane.showMessageDialog(this, "No booking selected to update.", "Update Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updatechangebookingActionPerformed

    public void cleardisplay() {

        UpdatePanel.setVisible(false);
    }
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        int selectedIndex = bookingComboBox.getSelectedIndex();
        if (selectedIndex >= 0) {
            List<BookingInfo> allBookings = getBookingsFromCSV();
            BookingInfo selectedBooking = allBookings.get(selectedIndex);
            String newTime = (String) jComboBoxTime.getSelectedItem();
            // Check if the booking is in the 'Cancelled' state
            if ("booked".equals(selectedBooking.status)) {
                // Update the booking with new  status to 'cancelled'
                selectedBooking.status = "cancelled";
                // Save the updated bookings to CSV
                saveBookingsToCSV(allBookings);
                JOptionPane.showMessageDialog(this, "Booking cancelled successfully.");
                displayBookings(allBookings); // Refresh the ComboBox display
            } else {
                // Notify the user that only bookings in 'Cancelled' state can be cancelled
                JOptionPane.showMessageDialog(this, "Only bookings in 'Booked' status can be cancelled.", "Cancellation Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No booking selected to change.", "Change Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBookings(00, 00).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdatePanel;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> bookingComboBox;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JComboBox<String> jComboBoxTime;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelTitlle;
    private javax.swing.JTextField jTextFieldLearnerID;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton updatechangebooking;
    // End of variables declaration//GEN-END:variables
}
